apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-verify
  name: kube-verify
  namespace: kube-verify
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: kube-verify
    spec:
      containers:
      - image: quay.io/clcollins/kube-verify:01
        name: nginx
        ports:
        - containerPort: 8080
